//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gym.Models.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class GymEntities : DbContext
    {
        public GymEntities()
            : base("name=GymEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Genero> Genero { get; set; }
        public virtual DbSet<Usuario> Usuario { get; set; }
        public virtual DbSet<CompraSuscripcion> CompraSuscripcion { get; set; }
        public virtual DbSet<Suscripcion> Suscripcion { get; set; }
        public virtual DbSet<SuscripcionUsuario> SuscripcionUsuario { get; set; }
        public virtual DbSet<HistorialReporteAsistencia> HistorialReporteAsistencia { get; set; }
    }
}
